import mods.gregtech.multiblock.Builder;
import mods.gregtech.multiblock.FactoryBlockPattern;
import mods.gregtech.multiblock.RelativeDirection;
import mods.gregtech.multiblock.functions.IPatternBuilderFunction;
import mods.gregtech.IControllerTile;
import mods.gregtech.multiblock.CTPredicate;
import mods.gregtech.multiblock.IBlockPattern;
import mods.gregtech.recipe.FactoryRecipeMap;
import mods.gregtech.recipe.RecipeMap;

// Multiblock crap
val ultimate_void_miner = Builder.start("mbt:ultimate_void_miner")
	.withPattern(function(controller as IControllerTile) as IBlockPattern {
			return FactoryBlockPattern.start()
				.aisle("CCCCC", "AAFAA", "AAFAA", "AAFAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA")
				.aisle("CCCCC", "AFXFA", "AFXFA", "AFXFA", "AAFAA", "AAFAA", "AAFAA", "AAAAA", "AAAAA", "AAAAA")
				.aisle("CCCCC", "FXXXF", "FXXXF", "FXXXF", "AFXFA", "AFXFA", "AFXFA", "AAFAA", "AAFAA", "AAFAA")
				.aisle("CCCCC", "AFXFA", "AFXFA", "AFXFA", "AAFAA", "AAFAA", "AAFAA", "AAAAA", "AAAAA", "AAAAA")
				.aisle("CCRCC", "AAFAA", "AAFAA", "AAFAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA", "AAAAA")
				.where('R', controller.self())
				.where("C", CTPredicate.states(<metastate:gcym:large_multiblock_casing:11>)
							| CTPredicate.abilities(<mte_ability:IMPORT_ITEMS>).setMaxGlobalLimited(1).setPreviewCount(1)
							| CTPredicate.abilities(<mte_ability:EXPORT_ITEMS>).setMinGlobalLimited(1).setPreviewCount(1)
							| CTPredicate.abilities(<mte_ability:INPUT_ENERGY>).setMinGlobalLimited(1).setPreviewCount(1) 
							| CTPredicate.abilities(<mte_ability:MAINTENANCE_HATCH>).setMinGlobalLimited(1).setMaxGlobalLimited(1).setPreviewCount(1)
							)
				.where("X", CTPredicate.states(<metastate:gcym:large_multiblock_casing:11>))
				.where("F", CTPredicate.states(<metastate:gregtech:meta_block_frame_7:15>))
				.where("A", CTPredicate.getAir())
				.build();
			} as IPatternBuilderFunction)
		.withRecipeMap(
			FactoryRecipeMap.start("ultimate_void_miner")
				.minOutputs(1)
				.maxOutputs(110)
				.minInputs(1)
				.maxInputs(1)
				.build())
		.withBaseTexture(<metastate:gcym:large_multiblock_casing:11>)
		.buildAndRegister();
		
ultimate_void_miner.hasMaintenanceMechanics = true;
ultimate_void_miner.hasMufflerMechanics = false;

<gregtech:machine:32001>.addTooltip("UHV Multiblock machine that'll mine a stack of every ore added by GregTech. Circuit 0 mines Overworld variants, Circuit 1 mines Nether variants, and Circuit 2 mines End variants. Uses 2,097,152 EU/t and takes exactly 1 minute to mine all the ores
");

// Recipe for the Multiblock controller
recipes.addShaped("vomr", <gregtech:machine:32001>, [[<gcym:large_multiblock_casing:11>, <ore:circuitUhv>, <gcym:large_multiblock_casing:11>], [<ore:circuitUhv>, <gregtech:machine:994>, <ore:circuitUhv>], [<gcym:large_multiblock_casing:11>, <ore:circuitUhv>, <gcym:large_multiblock_casing:11>]]);

// Recipes for the Multiblock itself
ultimate_void_miner.recipeMap.recipeBuilder()
	.duration(1200)
	.EUt(2097152)
	.circuit(0)
	.hidden()
	.outputs(<gregtech:ore_aluminium_0> * 64,
					  <gregtech:ore_beryllium_0> * 64,
					  <gregtech:ore_cobalt_0> * 64,
					  <gregtech:ore_copper_0> * 64,
					  <gregtech:ore_gold_0> * 64,
					  <gregtech:ore_iron_0> * 64,
					  <gregtech:ore_lead_0> * 64,
					  <gregtech:ore_lithium_0> * 64,
					  <gregtech:ore_molybdenum_0> * 64,
					  <gregtech:ore_neodymium_0> * 64,
					  <gregtech:ore_nickel_0> * 64,
					  <gregtech:ore_palladium_0> * 64,
					  <gregtech:ore_platinum_0> * 64,
					  <gregtech:ore_plutonium_0> * 64,
					  <gregtech:ore_silver_0> * 64,
					  <gregtech:ore_sulfur_0> * 64,
					  <gregtech:ore_thorium_0> * 64,
					  <gregtech:ore_tin_0> * 64,
					  <gregtech:ore_naquadah_0> * 64,
					  <gregtech:ore_certus_quartz_0> * 64,
					  <gregtech:ore_almandine_0> * 64,
					  <gregtech:ore_asbestos_0> * 64,
					  <gregtech:ore_banded_iron_0> * 64,
					  <gregtech:ore_blue_topaz_0> * 64,
					  <gregtech:ore_brown_limonite_0> * 64,
					  <gregtech:ore_calcite_0> * 64,
					  <gregtech:ore_cassiterite_0> * 64,
					  <gregtech:ore_cassiterite_sand_0> * 64,
					  <gregtech:ore_chalcopyrite_0> * 64,
					  <gregtech:ore_chromite_0> * 64,
					  <gregtech:ore_cinnabar_0> * 64,
					  <gregtech:ore_coal_0> * 64,
					  <gregtech:ore_cobaltite_0> * 64,
					  <gregtech:ore_cooperite_0> * 64,
					  <gregtech:ore_diamond_0> * 64,
					  <gregtech:ore_emerald_0> * 64,
					  <gregtech:ore_galena_0> * 64,
					  <gregtech:ore_garnierite_0> * 64,
					  <gregtech:ore_green_sapphire_0> * 64,
					  <gregtech:ore_grossular_0> * 64,
					  <gregtech:ore_ilmenite_0> * 64,
					  <gregtech:ore_bauxite_0> * 64,
					  <gregtech:ore_lazurite_0> * 64,
					  <gregtech:ore_magnesite_0> * 64,
					  <gregtech:ore_magnetite_0> * 64,
					  <gregtech:ore_molybdenite_0> * 64,
					  <gregtech:ore_powellite_0> * 64,
					  <gregtech:ore_pyrite_0> * 64,
					  <gregtech:ore_pyrolusite_0> * 64,
					  <gregtech:ore_pyrope_0> * 64,
					  <gregtech:ore_rock_salt_0> * 64,
					  <gregtech:ore_ruby_0> * 64,
					  <gregtech:ore_salt_0> * 64,
					  <gregtech:ore_saltpeter_0> * 64,
					  <gregtech:ore_sapphire_0> * 64,
					  <gregtech:ore_scheelite_0> * 64,
					  <gregtech:ore_sodalite_0> * 64,
					  <gregtech:ore_tantalite_0> * 64,
					  <gregtech:ore_spessartine_0> * 64,
					  <gregtech:ore_sphalerite_0> * 64,
					  <gregtech:ore_stibnite_0> * 64,
					  <gregtech:ore_tetrahedrite_0> * 64,
					  <gregtech:ore_topaz_0> * 64,
					  <gregtech:ore_tungstate_0> * 64,
					  <gregtech:ore_uraninite_0> * 64,
					  <gregtech:ore_wulfenite_0> * 64,
					  <gregtech:ore_yellow_limonite_0> * 64,
					  <gregtech:ore_nether_quartz_0> * 64,
					  <gregtech:ore_quartzite_0> * 64,
					  <gregtech:ore_graphite_0> * 64,
					  <gregtech:ore_bornite_0> * 64,
					  <gregtech:ore_chalcocite_0> * 64,
					  <gregtech:ore_realgar_0> * 64,
					  <gregtech:ore_bastnasite_0> * 64,
					  <gregtech:ore_pentlandite_0> * 64,
					  <gregtech:ore_spodumene_0> * 64,
					  <gregtech:ore_lepidolite_0> * 64,
					  <gregtech:ore_glauconite_sand_0> * 64,
					  <gregtech:ore_malachite_0> * 64,
					  <gregtech:ore_mica_0> * 64,
					  <gregtech:ore_barite_0> * 64,
					  <gregtech:ore_alunite_0> * 64,
					  <gregtech:ore_talc_0> * 64,
					  <gregtech:ore_soapstone_0> * 64,
					  <gregtech:ore_kyanite_0> * 64,
					  <gregtech:ore_pyrochlore_0> * 64,
					  <gregtech:ore_oilsands_0> * 64,
					  <gregtech:ore_olivine_0> * 64,
					  <gregtech:ore_opal_0> * 64,
					  <gregtech:ore_amethyst_0> * 64,
					  <gregtech:ore_lapis_0> * 64,
					  <gregtech:ore_apatite_0> * 64,
					  <gregtech:ore_tricalcium_phosphate_0> * 64,
					  <gregtech:ore_garnet_red_0> * 64,
					  <gregtech:ore_garnet_yellow_0> * 64,
					  <gregtech:ore_vanadium_magnetite_0> * 64,
					  <gregtech:ore_pollucite_0> * 64,
					  <gregtech:ore_bentonite_0> * 64,
					  <gregtech:ore_fullers_earth_0> * 64,
					  <gregtech:ore_pitchblende_0> * 64,
					  <gregtech:ore_monazite_0> * 64,
					  <gregtech:ore_trona_0> * 64,
					  <gregtech:ore_gypsum_0> * 64,
					  <gregtech:ore_zeolite_0> * 64,
					  <gregtech:ore_redstone_0> * 64,
					  <gregtech:ore_electrotine_0> * 64,
					  <gregtech:ore_diatomite_0> * 64,
					  <gregtech:ore_granitic_mineral_sand_0> * 64,
					  <gregtech:ore_garnet_sand_0> * 64,
					  <gregtech:ore_basaltic_mineral_sand_0> * 64)
	.buildAndRegister();
	
ultimate_void_miner.recipeMap.recipeBuilder()
	.duration(1200)
	.EUt(2097152)
	.circuit(1)
	.hidden()
	.outputs(<gregtech:ore_aluminium_0:1> * 64,
					  <gregtech:ore_beryllium_0:1> * 64,
					  <gregtech:ore_cobalt_0:1> * 64,
					  <gregtech:ore_copper_0:1> * 64,
					  <gregtech:ore_gold_0:1> * 64,
					  <gregtech:ore_iron_0:1> * 64,
					  <gregtech:ore_lead_0:1> * 64,
					  <gregtech:ore_lithium_0:1> * 64,
					  <gregtech:ore_molybdenum_0:1> * 64,
					  <gregtech:ore_neodymium_0:1> * 64,
					  <gregtech:ore_nickel_0:1> * 64,
					  <gregtech:ore_palladium_0:1> * 64,
					  <gregtech:ore_platinum_0:1> * 64,
					  <gregtech:ore_plutonium_0:1> * 64,
					  <gregtech:ore_silver_0:1> * 64,
					  <gregtech:ore_sulfur_0:1> * 64,
					  <gregtech:ore_thorium_0:1> * 64,
					  <gregtech:ore_tin_0:1> * 64,
					  <gregtech:ore_naquadah_0:1> * 64,
					  <gregtech:ore_certus_quartz_0:1> * 64,
					  <gregtech:ore_almandine_0:1> * 64,
					  <gregtech:ore_asbestos_0:1> * 64,
					  <gregtech:ore_banded_iron_0:1> * 64,
					  <gregtech:ore_blue_topaz_0:1> * 64,
					  <gregtech:ore_brown_limonite_0:1> * 64,
					  <gregtech:ore_calcite_0:1> * 64,
					  <gregtech:ore_cassiterite_0:1> * 64,
					  <gregtech:ore_cassiterite_sand_0:1> * 64,
					  <gregtech:ore_chalcopyrite_0:1> * 64,
					  <gregtech:ore_chromite_0:1> * 64,
					  <gregtech:ore_cinnabar_0:1> * 64,
					  <gregtech:ore_coal_0:1> * 64,
					  <gregtech:ore_cobaltite_0:1> * 64,
					  <gregtech:ore_cooperite_0:1> * 64,
					  <gregtech:ore_diamond_0:1> * 64,
					  <gregtech:ore_emerald_0:1> * 64,
					  <gregtech:ore_galena_0:1> * 64,
					  <gregtech:ore_garnierite_0:1> * 64,
					  <gregtech:ore_green_sapphire_0:1> * 64,
					  <gregtech:ore_grossular_0:1> * 64,
					  <gregtech:ore_ilmenite_0:1> * 64,
					  <gregtech:ore_bauxite_0:1> * 64,
					  <gregtech:ore_lazurite_0:1> * 64,
					  <gregtech:ore_magnesite_0:1> * 64,
					  <gregtech:ore_magnetite_0:1> * 64,
					  <gregtech:ore_molybdenite_0:1> * 64,
					  <gregtech:ore_powellite_0:1> * 64,
					  <gregtech:ore_pyrite_0:1> * 64,
					  <gregtech:ore_pyrolusite_0:1> * 64,
					  <gregtech:ore_pyrope_0:1> * 64,
					  <gregtech:ore_rock_salt_0:1> * 64,
					  <gregtech:ore_ruby_0:1> * 64,
					  <gregtech:ore_salt_0:1> * 64,
					  <gregtech:ore_saltpeter_0:1> * 64,
					  <gregtech:ore_sapphire_0:1> * 64,
					  <gregtech:ore_scheelite_0:1> * 64,
					  <gregtech:ore_sodalite_0:1> * 64,
					  <gregtech:ore_tantalite_0:1> * 64,
					  <gregtech:ore_spessartine_0:1> * 64,
					  <gregtech:ore_sphalerite_0:1> * 64,
					  <gregtech:ore_stibnite_0:1> * 64,
					  <gregtech:ore_tetrahedrite_0:1> * 64,
					  <gregtech:ore_topaz_0:1> * 64,
					  <gregtech:ore_tungstate_0:1> * 64,
					  <gregtech:ore_uraninite_0:1> * 64,
					  <gregtech:ore_wulfenite_0:1> * 64,
					  <gregtech:ore_yellow_limonite_0:1> * 64,
					  <gregtech:ore_nether_quartz_0:1> * 64,
					  <gregtech:ore_quartzite_0:1> * 64,
					  <gregtech:ore_graphite_0:1> * 64,
					  <gregtech:ore_bornite_0:1> * 64,
					  <gregtech:ore_chalcocite_0:1> * 64,
					  <gregtech:ore_realgar_0:1> * 64,
					  <gregtech:ore_bastnasite_0:1> * 64,
					  <gregtech:ore_pentlandite_0:1> * 64,
					  <gregtech:ore_spodumene_0:1> * 64,
					  <gregtech:ore_lepidolite_0:1> * 64,
					  <gregtech:ore_glauconite_sand_0:1> * 64,
					  <gregtech:ore_malachite_0:1> * 64,
					  <gregtech:ore_mica_0:1> * 64,
					  <gregtech:ore_barite_0:1> * 64,
					  <gregtech:ore_alunite_0:1> * 64,
					  <gregtech:ore_talc_0:1> * 64,
					  <gregtech:ore_soapstone_0:1> * 64,
					  <gregtech:ore_kyanite_0:1> * 64,
					  <gregtech:ore_pyrochlore_0:1> * 64,
					  <gregtech:ore_oilsands_0:1> * 64,
					  <gregtech:ore_olivine_0:1> * 64,
					  <gregtech:ore_opal_0:1> * 64,
					  <gregtech:ore_amethyst_0:1> * 64,
					  <gregtech:ore_lapis_0:1> * 64,
					  <gregtech:ore_apatite_0:1> * 64,
					  <gregtech:ore_tricalcium_phosphate_0:1> * 64,
					  <gregtech:ore_garnet_red_0:1> * 64,
					  <gregtech:ore_garnet_yellow_0:1> * 64,
					  <gregtech:ore_vanadium_magnetite_0:1> * 64,
					  <gregtech:ore_pollucite_0:1> * 64,
					  <gregtech:ore_bentonite_0:1> * 64,
					  <gregtech:ore_fullers_earth_0:1> * 64,
					  <gregtech:ore_pitchblende_0:1> * 64,
					  <gregtech:ore_monazite_0:1> * 64,
					  <gregtech:ore_trona_0:1> * 64,
					  <gregtech:ore_gypsum_0:1> * 64,
					  <gregtech:ore_zeolite_0:1> * 64,
					  <gregtech:ore_redstone_0:1> * 64,
					  <gregtech:ore_electrotine_0:1> * 64,
					  <gregtech:ore_diatomite_0:1> * 64,
					  <gregtech:ore_granitic_mineral_sand_0:1> * 64,
					  <gregtech:ore_garnet_sand_0:1> * 64,
					  <gregtech:ore_basaltic_mineral_sand_0:1> * 64)
	.buildAndRegister();
	
ultimate_void_miner.recipeMap.recipeBuilder()
	.duration(1200)
	.EUt(2097152)
	.circuit(2)
	.hidden()
	.outputs(<gregtech:ore_aluminium_0:2> * 64,
					  <gregtech:ore_beryllium_0:2> * 64,
					  <gregtech:ore_cobalt_0:2> * 64,
					  <gregtech:ore_copper_0:2> * 64,
					  <gregtech:ore_gold_0:2> * 64,
					  <gregtech:ore_iron_0:2> * 64,
					  <gregtech:ore_lead_0:2> * 64,
					  <gregtech:ore_lithium_0:2> * 64,
					  <gregtech:ore_molybdenum_0:2> * 64,
					  <gregtech:ore_neodymium_0:2> * 64,
					  <gregtech:ore_nickel_0:2> * 64,
					  <gregtech:ore_palladium_0:2> * 64,
					  <gregtech:ore_platinum_0:2> * 64,
					  <gregtech:ore_plutonium_0:2> * 64,
					  <gregtech:ore_silver_0:2> * 64,
					  <gregtech:ore_sulfur_0:2> * 64,
					  <gregtech:ore_thorium_0:2> * 64,
					  <gregtech:ore_tin_0:2> * 64,
					  <gregtech:ore_naquadah_0:2> * 64,
					  <gregtech:ore_certus_quartz_0:2> * 64,
					  <gregtech:ore_almandine_0:2> * 64,
					  <gregtech:ore_asbestos_0:2> * 64,
					  <gregtech:ore_banded_iron_0:2> * 64,
					  <gregtech:ore_blue_topaz_0:2> * 64,
					  <gregtech:ore_brown_limonite_0:2> * 64,
					  <gregtech:ore_calcite_0:2> * 64,
					  <gregtech:ore_cassiterite_0:2> * 64,
					  <gregtech:ore_cassiterite_sand_0:2> * 64,
					  <gregtech:ore_chalcopyrite_0:2> * 64,
					  <gregtech:ore_chromite_0:2> * 64,
					  <gregtech:ore_cinnabar_0:2> * 64,
					  <gregtech:ore_coal_0:2> * 64,
					  <gregtech:ore_cobaltite_0:2> * 64,
					  <gregtech:ore_cooperite_0:2> * 64,
					  <gregtech:ore_diamond_0:2> * 64,
					  <gregtech:ore_emerald_0:2> * 64,
					  <gregtech:ore_galena_0:2> * 64,
					  <gregtech:ore_garnierite_0:2> * 64,
					  <gregtech:ore_green_sapphire_0:2> * 64,
					  <gregtech:ore_grossular_0:2> * 64,
					  <gregtech:ore_ilmenite_0:2> * 64,
					  <gregtech:ore_bauxite_0:2> * 64,
					  <gregtech:ore_lazurite_0:2> * 64,
					  <gregtech:ore_magnesite_0:2> * 64,
					  <gregtech:ore_magnetite_0:2> * 64,
					  <gregtech:ore_molybdenite_0:2> * 64,
					  <gregtech:ore_powellite_0:2> * 64,
					  <gregtech:ore_pyrite_0:2> * 64,
					  <gregtech:ore_pyrolusite_0:2> * 64,
					  <gregtech:ore_pyrope_0:2> * 64,
					  <gregtech:ore_rock_salt_0:2> * 64,
					  <gregtech:ore_ruby_0:2> * 64,
					  <gregtech:ore_salt_0:2> * 64,
					  <gregtech:ore_saltpeter_0:2> * 64,
					  <gregtech:ore_sapphire_0:2> * 64,
					  <gregtech:ore_scheelite_0:2> * 64,
					  <gregtech:ore_sodalite_0:2> * 64,
					  <gregtech:ore_tantalite_0:2> * 64,
					  <gregtech:ore_spessartine_0:2> * 64,
					  <gregtech:ore_sphalerite_0:2> * 64,
					  <gregtech:ore_stibnite_0:2> * 64,
					  <gregtech:ore_tetrahedrite_0:2> * 64,
					  <gregtech:ore_topaz_0:2> * 64,
					  <gregtech:ore_tungstate_0:2> * 64,
					  <gregtech:ore_uraninite_0:2> * 64,
					  <gregtech:ore_wulfenite_0:2> * 64,
					  <gregtech:ore_yellow_limonite_0:2> * 64,
					  <gregtech:ore_nether_quartz_0:2> * 64,
					  <gregtech:ore_quartzite_0:2> * 64,
					  <gregtech:ore_graphite_0:2> * 64,
					  <gregtech:ore_bornite_0:2> * 64,
					  <gregtech:ore_chalcocite_0:2> * 64,
					  <gregtech:ore_realgar_0:2> * 64,
					  <gregtech:ore_bastnasite_0:2> * 64,
					  <gregtech:ore_pentlandite_0:2> * 64,
					  <gregtech:ore_spodumene_0:2> * 64,
					  <gregtech:ore_lepidolite_0:2> * 64,
					  <gregtech:ore_glauconite_sand_0:2> * 64,
					  <gregtech:ore_malachite_0:2> * 64,
					  <gregtech:ore_mica_0:2> * 64,
					  <gregtech:ore_barite_0:2> * 64,
					  <gregtech:ore_alunite_0:2> * 64,
					  <gregtech:ore_talc_0:2> * 64,
					  <gregtech:ore_soapstone_0:2> * 64,
					  <gregtech:ore_kyanite_0:2> * 64,
					  <gregtech:ore_pyrochlore_0:2> * 64,
					  <gregtech:ore_oilsands_0:2> * 64,
					  <gregtech:ore_olivine_0:2> * 64,
					  <gregtech:ore_opal_0:2> * 64,
					  <gregtech:ore_amethyst_0:2> * 64,
					  <gregtech:ore_lapis_0:2> * 64,
					  <gregtech:ore_apatite_0:2> * 64,
					  <gregtech:ore_tricalcium_phosphate_0:2> * 64,
					  <gregtech:ore_garnet_red_0:2> * 64,
					  <gregtech:ore_garnet_yellow_0:2> * 64,
					  <gregtech:ore_vanadium_magnetite_0:2> * 64,
					  <gregtech:ore_pollucite_0:2> * 64,
					  <gregtech:ore_bentonite_0:2> * 64,
					  <gregtech:ore_fullers_earth_0:2> * 64,
					  <gregtech:ore_pitchblende_0:2> * 64,
					  <gregtech:ore_monazite_0:2> * 64,
					  <gregtech:ore_trona_0:2> * 64,
					  <gregtech:ore_gypsum_0:2> * 64,
					  <gregtech:ore_zeolite_0:2> * 64,
					  <gregtech:ore_redstone_0:2> * 64,
					  <gregtech:ore_electrotine_0:2> * 64,
					  <gregtech:ore_diatomite_0:2> * 64,
					  <gregtech:ore_granitic_mineral_sand_0:2> * 64,
					  <gregtech:ore_garnet_sand_0:2> * 64,
					  <gregtech:ore_basaltic_mineral_sand_0:2> * 64)
	.buildAndRegister();